### ISSUE TITLE
等高多栏布局

### ISSUE THREAD

**Issue by xiaokk06** [xiaokk06/blog#10]
### 等高布局
&emsp;&emsp;多栏布局的使用和等高框有着密不可分的关系(多栏不等高布局一般指的就是瀑布流布局了)，接下来对等高布局做一个基本的介绍。

1. flex布局
&ensp;&ensp;在分栏布局的最后一种实现方式里里面提到的浮动布局实际上也是等高布局：
实现方式忽略，demo地址：http://codepen.io/xiaokk06/pen/RGgJxW

2. 使用table或者伪table
&ensp;&ensp;使用table或为伪table不仅可以实现等高布局，也可以实现上一篇文章介绍的多栏布局。其实table布局基本在很早的时候就会接触到，
但是使用得比较少，其原因就在于table的嵌套结构太多，html冗杂，又不利于DOM的操作和渲染，用来布局一般情况下也不是很符合语义。伪table
布局和table布局类似，只不过借助于css，可以让我们不直接使用table tr td这些直接的表格元素，而是通过display: table, display: table-row, 
display: table-cell，改变元素的显示特性，让浏览器把这些元素当成table来渲染，这种渲染的表现跟用真实的table没有啥区别，就连那些table专用
的css属性，比如table-layout，border-collapse和border-spacing，都能产生效果。
* 可用于伪table的display属性值
- table:作为块级表格显示，表格前后带有换行符
- inline-tale:内联表格显示，前后没有换行符
- table-row-group:作为一个或多个行的分组显示，类似tbody
- table-header-group:作为一个或多个行的分组显示，类似thead
- table-footer-group:作为一个或多个行的分组显示，类似tfoot
- table-row:作为一个表格行显示，类似tr
- table-column-group:作为一个或多个列的分组来显示，类似colgroup
- table-column:作为一个单元格列显示，类似col
- table-cell:作为一个表格单元显示，类似td
- table-caption:作为一个表格标题显示，类似caption
* 当元素被设置为上面列出的值的时候，就可以把目标元素作为属性对应的表格元素看待
* **table-cell会被float, position:absolute破坏，所以这些属性不能同时使用**
* 使用这些伪table属性时，可以单独使用某一个属性浏览器会在这些元素的外层包裹缺失的框来保证伪table元素框嵌套结构的完整性，这些框跟常提到的行
框一样都是不可见的，网上有的文章里也把这种做法叫做匿名表格。

示例代码：

```css
.tb-cell {
    display: table-cell;
    padding: 10px;
    border: 1px solid #ccc;
}
```
```html
<div class="tb-cell">这是第1个display: table-cell;的元素。</div>
<div class="tb-cell">这是第2个display: table-cell;的元素。</div>
```
demo地址：http://codepen.io/xiaokk06/pen/bwopRE 
从示例效果中可以看到完全是等高布局

下面是3栏布局的示例：
```html
<header>顶部</header>
<aside class="layout__col layout__aside layout__aside--left">左侧边栏宽度固定</aside>
<div class="layout__col layout__main">内容栏宽度自适应<br>高度增加一点，旁边的高度都会自动增加</div>
<aside class="layout__col layout__aside layout__aside--right">右侧边栏宽度固定</aside>
<footer>底部</footer>
```

```css
.layout__col {
  text-align: center;
  display: table-cell;
  /**
  这里设置line-height时就按照设置的值进行显示
  不设置时即按照最大高度栏高度布局
  */
  line-height: 50px;
}

.layout__col + .layout__col {
  border-left: 10px solid #fff;
}

.layout__main {
  width: 3000px;
  background-color: #4DBCB0;
}

.layout__aside {
  width: 200px;
  min-width: 200px;
  background-color: #daf1ef;
}
```
demo地址:http://codepen.io/xiaokk06/pen/xEXVPa

由于匿名表格的作用，导致采用伪table布局的方法变得非常简洁。兼容性方面，不考虑IE8及以下，其它浏览器几乎没有问题。

3. 使用绝对定位
分栏自适应有两个原则：第一是主体内容栏宽度自适应，这点绝对定位是可以做到的；第二点是所有栏的高度都能动态变化，并且不能导致父容器高度塌陷，不能在各栏内
部出现滚动或溢出的情况，这点绝对定位不容易做到适用所有场景。而本文又把这种布局方法拿出来介绍，是因为绝对定位做等高布局很容易，所以用绝对定位做等高分栏
布局是一种可行的办法，只是这种方法适用的场景有一些限制，需要根据实际情况考虑是否要采用。
- 所有栏都采用绝对定位
```html
<div class="layout">
  <aside class="layout__aside layout__aside--left">左侧边栏宽度固定</aside>
  <div class="layout__main">内容栏宽度自适应</div>
  <aside class="layout__aside layout__aside--right">右侧边栏宽度固定</aside>
</div>
```

```css
.layout {
  height: 300px;
  position: relative;
}

.layout__aside,
.layout__main {
  position: absolute;
  top: 0;
  bottom: 0;
}

.layout__main {
  left: 210px;
  right: 210px;
  background-color:lightgreen;
}

.layout__aside {
  width: 200px;
  background-color:lightblue;
}

.layout__aside--left {
  left: 0;
}

.layout__aside--right {
  right: 0;
}
```
demo地址:http://codepen.io/xiaokk06/pen/ORxXQx
这种布局的特点是：**主体内容自适应布局，所有栏登高，不过必须给父元素定义一个高度**，适用场景为父元素高度已知或全屏。

- 侧边栏绝对定位，主体内容栏保持流式布局
```html
<div class="layout">
  <aside class="layout__aside layout__aside--left">左侧边栏宽度固定</aside>
  <div class="layout__main">内容栏宽度自适应<br>高度增加一点，旁边的高度都会自动增加</div>
  <aside class="layout__aside layout__aside--right">右侧边栏宽度固定</aside>
</div>
```

```css
.layout {
  position: relative;
}

.layout__aside {
  position: absolute;
  top: 0;
  bottom: 0;
}

.layout__main {
  margin: 0 210px;
  background-color:lightgreen;
}

.layout__aside {
  width: 200px;
  background-color:lightblue;
}

.layout__aside--left {
  left: 0;
}

.layout__aside--right {
  right: 0;
}
```
上面的代码中，layout__main通过magin来给侧边栏留出空间，其实也可以在layout元素上添加padding来处理，作用是一样的。这个方法
相比前一个方法好一点的是，父元素的高度可以通过主体内容栏给撑起来，不过由此也带来了一个新问题，就是内容栏高度不够的时候，侧
边栏就会出现溢出或者滚动，解决这个新问题的办法有2个：第一，如果侧边栏的内容都是已知的，并且没有折叠展开这种会改变侧边栏内容
高度的功能，那么可以给layout设置一个min-height来处理；第二，如果侧边栏的内容是动态的，除了给layout加min-height之外，还得在
每次改变侧边栏内容的时候，主动去调整主体内容栏的高度，如果主体内容栏的高度小于侧边栏的高度，就要更新主体内容栏的高度。不过如
果你的内容栏的内容很多，侧边栏内容较少的话，就不用考虑这个新问题了。

绝对定位的做法就是这样，第一种限制较高；第二种稍微强一些，在一些场景下，可能还得借助JS来处理，所以综合起来不算是一个非常好的
方式。只有你的布局需求恰好满足它的条件时，可能才会考虑使用它。

4. 借助边框，背景实现假等高
不过回看一下多栏布局内容的话，上文提到的3种布局方式：圣杯布局，双飞翼布局，float布局，不用JS的话，就无法做到这种完全等高的
效果。这三种布局，只能考虑借助边框和背景实现视觉上的等高，也就是假等高的做法。毕竟从效果上来说，如果没有设置背景和边框的话，
即使是完全等高，视觉上也看不出来，所以假等高的做法是值得采用的。

- 利用背景图片
以布局容器宽度固定的左中右三栏布局说明这个做法的步骤，首先制作一张高度较小，宽度跟布局容器宽度相同的背景图片，把这张图片作为
布局容器的背景图垂直平铺。这张背景图要求跟页面一样也是分栏，而且每栏的宽度和栏之间的间隔都跟页面布局里面的栏位宽度和栏位间隔
相同，这样才能保证，背景图片的每个栏位与页面里面的每个栏位重合。因为页面里面的每个栏位底下，都有一个背景图片的栏位跟它对应，
所以即使某一栏高度不够，但是视觉上这个栏位的高度跟布局容器的高度是相同的，这就是借助背景图来达到视觉等高的原理。这个做法的经
典例子就是http://www.w3school.com.cn/。

- 利用边框重叠
这个做法，适合要用边框来呈现等高效果的布局，也就是说各栏不能有背景，否则看起来边框是等高了，但是背景没有等高。它的原理要分成
两部分来说，如果是2栏布局，做法比较简单，比如左右分栏的布局，给侧边栏加一个右边框，给内容栏加一个左边框，然后给内容栏加上负
的margin-left，让2个边框重合，这样不管哪个栏位内容多，边框重叠之后的高度就跟整体的高度一致了，也就达到了我们想要的等高效果；
如果是多栏布局，这种边框重叠的方式不能做到所有场景下的视觉等高，比如说左中右三栏布局，现在是按边框重叠的办法实现了下等高，当
左边栏的内容动态增加很多时，右边侧边栏跟内容栏的边框整体高度，并不会动态增加，然后就会形成错层的效果，对于这种情况，可以利用
绝对定位，用额外的空元素模拟栏与栏之间的边框效果。
(1)2栏布局，侧边栏固定在左边，右侧是主体内容栏：
```html
<div class="layout">
    <aside class="layout__aside">侧边栏宽度固定</aside>
    <div class="layout__main">内容栏宽度自适应<br>高度增加一点，旁边的高度看起来都跟内容栏高度一样</div>
</div>
```

```css
 .layout:after {
   content: " ";
   clear: both;
   display: table;
 }
 
 .layout__aside,
 .layout__main {
   float: left;
 }
 
 .layout {
   padding-left: 201px;
 }
 
 .layout__main {
   width: 100%;
   margin-left: -1px;
   border-left: 1px solid #ccc;
   background-color: lightgreen;
 }
 
 .layout__aside {
   width: 200px;
   border-right: 1px solid #ccc;
   margin-left: -201px;
   background-color: lightblue;
 }
 ```

 在存在背景的时候我们可以很明显得看到实际上两者的高度并不一致，只是边框重合会有一种等高的错觉。这也就印证了这种方式应用在没
 有背景的情况下。

(2)3栏布局，2个侧边栏分别固定在左边和右边，中间是主体内容栏：

```html
<div class="layout">
  <aside class="layout__division layout__division--left"></aside>
  <aside class="layout__division layout__division--right"></aside>
  <aside class="layout__aside layout__aside--left">左侧边栏宽度固定<br>再加点东西<br>再加点东西</aside>
  <div class="layout__main">内容栏宽度自适应<br>高度增加一点</div>
  <aside class="layout__aside layout__aside--right">右侧边栏宽度固定</aside>
</div>
```

```css
.layout:after {
        content: " ";
        clear: both;
        display: table;
    }
    .layout__aside, .layout__main {
        float: left;
        height: 100%;
    }
    .layout {
        padding:0 201px;
        position: relative;
    }
    .layout__main {
        width: 100%;
    }
    .layout__aside {
        width: 200px;
    }
    .layout__aside--left {
        margin-left: -201px;
    }
    .layout__aside--right {
        margin-right: -201px;
        float: right;
    }
    .layout__division {
        position: absolute;
        border-left: 1px solid #ccc;
        height: 100%;
    }
    .layout__division--left {
        left:200px;
    }
    .layout__division--right {
        right:200px;
    }
    ```

    demo地址：http://codepen.io/xiaokk06/pen/EgwNQR
    这种方式主要缺点在于增加了没有用的元素，所以并不推荐

    (3)利用padding值和margin值相互抵消，设置overflow:hidden
    ```html
    <div class="layout">
    <aside class="layout__aside box">侧边栏宽度固定</aside>
    <div class="layout__main box">内容栏宽度自适应<br>高度增加一点，旁边的高度看起来都跟内容栏高度一样</div>
</div>
```

```css
 .layout:after {
   content: " ";
   clear: both;
   display: table;
 }
 
 .layout__aside,
 .layout__main {
   float: left;
 }
 
 .layout {
   padding-left: 210px;
   height:200px;
 }
 
 .layout__main {
   width: 100%;
   background-color: lightgreen;
 }
 
 .layout__aside {
   width: 200px;
   margin-left: -210px;
   background-color: lightblue;
 }

.box{
  padding-bottom:999px;
  margin-bottom:-999px;
  overflow:hidden;
}
```

优点：可以制作带有边框的两列等高布局，并能兼容所有浏览器，结构简单明了。
缺点：这种方法存在一个很大的缺陷，那就是如果要实现每列四周有边框效果，那么每列的底部（或顶部）将无法有边框效果。
两种解决方法：第一种是使用背景图来模仿底部（或顶部）边框；第二种方法是使用div来模仿列的边框

demo地址：http://codepen.io/xiaokk06/pen/yazaAO

### 总结
其实还有一些其他的方法也可以实现上面所说的等高布局，只要对css属性足够熟悉，自己应该也可以想到一些amazing的想法，而
这也是我之后要努力去做到的。

参考连接：http://web.jobbole.com/85031/
