### ISSUE TITLE
CSS实现Scroll Indicator(滚动指示器) 

### ISSUE THREAD

**Issue by xiaokk06** [xiaokk06/blog#3]
# CSS实现Scroll Indicator(滚动指示器) 

&ensp;&ensp;之前在阮大神的ES6入门电子书上有看到顶部有一个进度条提示当前阅读本章的进度，想了一下觉得大致的实现原理应该是利用滚动条滚动的距离和当前
页面高度之间的比值来设置不同的宽度，从而达到提示进度的效果，今天偶然在W3Cplus论坛上看到用css实现的，大致研究了一下，在这里做个记录。

#### 主要原理
&ensp;&ensp;利用<a href="http://caniuse.com/#search=linear-gradient" target="_blank">linear-gardient</a>实现渐变的背景然后控制显示区域就可以了。由于在最后一屏的时候进度条应该全满，而进度条又显示在顶部，所
以这里进度条的background-size的高度应该设置为calc(100% - 100vh )，这个时候我们可以看到两种颜色斜向平分整个body元素，但是此时显示的效果并不是我们所
需要的效果，只有顶部那几个像素高度的变化是我们需要的最终效果，所以得给body元素加上一个蒙层来隐藏不需要的部分，这里我们使用一个::before来实现蒙层，
设置背景颜色和z-index来实现隐藏，同事还要给进度栏设置高度，因此top值设置为3个像素即可，而为了在最后一屏的时候不为空，需要给body的背景元素的高度加
上不少于进度条高度的像素值，因此最终的背景高度为calc(100% - 100vh + 4px)，此时效果就是我们需要的效果了。

&ensp;&ensp;主要代码如下：
```css
   body {
        background: linear-gradient(to right top, #0089f2 50%, #DDD 50%);
        background-size: 100% calc(100% - 100vh + 4px);
        background-repeat: no-repeat;
    }
    body::before {
        content: '';
        position: fixed;
        top: 3px;
        bottom: 0;
        width: 100%;
        z-index: -1;
        background: white;
    }
```

参考链接：[scrollIndicator](http://www.w3cplus.com/css/pure-css-create-scroll-indicator.html?sukey=3997c0719f1515201eee29f3340819bb76af58b600b4879c26169cad8fec3b159b5c93cb456f7cc24a4b9ceb0adcb5c5)
