### ISSUE TITLE
多栏布局实现方式

### ISSUE THREAD

**Issue by xiaokk06** [xiaokk06/blog#9]
### grid_layout
&emsp;&emsp;面试的时候一直被问到圣杯布局的问题，之前自己有实现过一些，但是并没有很全面，发现面试的时候问得还是比较细的，所以就总结一些圣杯布局的特点吧(并没有'人如其名'的感觉)。

&emsp;&emsp;主要适用场景：**侧边栏固定，主体内容自适应**。

##### 传统实现方式
1. 2栏布局，侧边栏固定在左边，右边是主体内容栏。
```html
<div class="layout">
    <aside class="layout__aside">侧边栏宽度固定</aside>
    <div class="layout__main">主内容栏宽度自适应</div>
</div>
```
对应样式如下：
```css
    .layout:after {
        clear: both;
        content: " ";
        display: table;
    }
    .layout__aside, .layout__main {
        float: left;
    }
    .layout {
        padding-left: 210px;
    }
    .layout__main {
        width: 100%;
    }
    .layout__aside {
        width: 200px;
        margin-left: -210px;
    }
```
2. 2栏布局，侧边栏固定在右边，左侧是主体内容栏，实现过程略，原理同上
3. 3栏布局，2个侧边栏分别固定在左边和右边，中间是主体内容栏
4. 3栏布局，2个侧边栏同时固定在左边，右边是主体内容栏
5. 3栏布局，2个侧边栏同时固定在右边，左边是主体内容栏

##### 实现原理
* layout元素根据分栏的要求设置合适的padding，需要配置对应的padding-left
* layout_main和layout_aside元素都需要浮动
* 两者的顺序也很关键
* layout_aside需要根据分栏布局呀排球，配置盒子的margin-left或margin-right

##### 双飞翼布局：3栏布局，2个侧边栏分别固定在左边和右边，中间是主体内容栏
实现方式如下：基本DOM结构
```html
<div class="layout__main-wrapper">
    <div class="layout__main">主内容栏宽度自适应</div>
</div>
<aside class="layout__aside layout__aside--left">左侧边栏宽度固定</aside>
<aside class="layout__aside layout__aside--right">右侧边栏宽度固定</aside>
<footer class="clear">底部</footer>
```
CSS样式
```css
.clear {
        clear: both;
    }
    .layout__main-wrapper,.layout__aside {
        float: left;
    }
    .layout__main-wrapper {
        width: 100%;
    }
    .layout__main {
        margin: 0 210px;
    }
    .layout__aside {
        width: 200px;
    }
    .layout__aside--left {
        margin-left: -100%;
    }
    .layout__aside--right {
        margin-left: -200px;
    }
```
##### 布局技巧
* 可以没有layout这一层包裹元素
* 浮动清除需要在外部元素上处理
* float和margin属性的设置方向相对统一，基本都是一个方向即可
* 还需要借助position:relative才可以

demo地址:http://codepen.io/xiaokk06/pen/PGKoJE

#### 纯浮动实现
前面的布局都有共同点:
* layout_main或layout_main_wrapper和layout_aside都会同时浮动
* 都需要借助负值属性实现
更简洁的做法是**只需要浮动layout_aside，给layout_main加上合适的margin值，就可以利用浮动元素的特性，完成想要的分栏布局效果**。

具体实现如下：
htmlDOM结构：
```html
<aside class="layout__aside layout__aside--left">左侧边栏宽度固定</aside>
<aside class="layout__aside layout__aside--right">右侧边栏宽度固定</aside>
<div class="layout__main">主内容栏宽度自适应</div>
<footer class="clear">底部</footer>
```
CSS样式
```css
 .clear {
        clear: both;
    }
 
    .layout__main {
        margin: 0 210px;
    }
 
    .layout__aside--left {
        width: 200px;
        float: left;
    }
 
    .layout__aside--right {
        width: 200px;
        float: right;
    }
```

#### flex布局
IE8不支持，IE11部分支持，其他浏览器比较新的版本都支持，这说明在绝大多数浏览器下，flex都可以发挥其强大的能力来实现多列布局。

具体实现如下：
DOM结构
```html
<div class="layout">
    <aside class="layout__aside">侧边栏宽度固定</aside>
    <div class="layout__main">主内容栏宽度自适应</div>
</div>
```
CSS样式
```css
.layout {
        display: flex;
    }
    .layout__main {
        flex: 1;
    }
    .layout__aside {
        width: 200px;
    }
    .layout > .layout__aside:not(:first-child),
    .layout > .layout__main:not(:first-child){
        margin-left: 10px;
    }
    ```
 效果与示例传统实现的第一种布局一致，而且左右元素等高。demo地址：http://codepen.io/xiaokk06/pen/RGgJxW
